name: Deploy To Server
on:
  push:
    branches:
    - main
jobs:
  deploy-to-server:
    environment: jordanwelch.com server
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment on server
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          command: bash ./deploy-scripts/deploy.sh jordanwelch.com
          host: ${{ secrets.HOST }}
          username: dploy
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}

